"""Update prioridad to allow null values

Revision ID: 8c087b2ea5d8
Revises: c5d9cdcc1e38
Create Date: 2024-07-29 22:40:48.360476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c087b2ea5d8'
down_revision = 'c5d9cdcc1e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('prioridad',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('prioridad',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
